package telas;

/**
 *
 * @author USER
 */
public class funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form funcionarios
     */
    listagem lis;
    public funcionarios(listagem l) {
        initComponents();
        this.lis = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnatendente = new javax.swing.JButton();
        btnbarbeiro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JButton();
        btngerente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnatendente.setText("Atendente");
        btnatendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatendenteActionPerformed(evt);
            }
        });

        btnbarbeiro.setText("Barbeiro");
        btnbarbeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarbeiroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cadadastro de Funcionarios");

        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        btngerente.setText("Gerente");
        btngerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnatendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnbarbeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btngerente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnvoltar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnatendente)
                .addGap(18, 18, 18)
                .addComponent(btnbarbeiro)
                .addGap(18, 18, 18)
                .addComponent(btngerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnvoltar)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        
        lis.atualizarDados();
        lis.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnatendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatendenteActionPerformed
        
        atendentes at = new atendentes(this);
        at.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnatendenteActionPerformed

    private void btnbarbeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarbeiroActionPerformed
        
        barbeiros b = new barbeiros(this);
        b.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnbarbeiroActionPerformed

    private void btngerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngerenteActionPerformed
        
        gerentes g = new gerentes(this);
        g.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btngerenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatendente;
    private javax.swing.JButton btnbarbeiro;
    private javax.swing.JButton btngerente;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
