/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import connect.coringaJPA;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import modelos.*;

/**
 *
 * @author USER
 */
public class listagem extends javax.swing.JFrame {

    /**
     * Creates new form listagem
     */
               private DefaultTableModel table;
           coringaJPA<atendimento> a = new coringaJPA<>(atendimento.class);

    private usuario usu;
    public listagem(usuario u) {
        initComponents();
        usu = u;
        
        iniciartabela();

        if (usu.getTipo().equalsIgnoreCase("Gerente")) {
            btnatendimento.setEnabled(true);
            btnexcluir.setEnabled(true);
            btnfuncionarios.setEnabled(true);
            btnservicos.setEnabled(true);
        } else if (usu.getTipo().equalsIgnoreCase("Atendente")) {
            btnatendimento.setEnabled(true);
            btnfuncionarios.setEnabled(false);            
            btnexcluir.setEnabled(false);
            btnservicos.setEnabled(false);
        } else {
            btnatendimento.setEnabled(false);
            btnfuncionarios.setEnabled(false);
            btnexcluir.setEnabled(false);
            btnservicos.setEnabled(false);
        }
    }

    public String getUsu(){
        return usu.getLogin();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jComboBox1 = new javax.swing.JComboBox<>();
        scroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbmbarbeiro = new javax.swing.JComboBox<>();
        cbmstatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnbusca = new javax.swing.JButton();
        btnlimpa = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnatendimento = new javax.swing.JButton();
        btnfuncionarios = new javax.swing.JButton();
        btncliente = new javax.swing.JButton();
        txtdata = new javax.swing.JFormattedTextField();
        btnservicos = new javax.swing.JButton();
        btnfechar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tabela);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA DE AGENDAMENTO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("BARBEIRO");

        jLabel3.setText("CLIENTE");

        jLabel4.setText("DATA");

        cbmbarbeiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Item 2", "Item 3", "Item 4" }));
        cbmbarbeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmbarbeiroActionPerformed(evt);
            }
        });

        cbmstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Aberto", "Fechado" }));
        cbmstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmstatusActionPerformed(evt);
            }
        });

        jLabel5.setText("STATUS");

        btnbusca.setText("PESQUISAR");
        btnbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaActionPerformed(evt);
            }
        });

        btnlimpa.setText("LIMPAR FILTROS");
        btnlimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpaActionPerformed(evt);
            }
        });

        btnexcluir.setText("EXCLUIR");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnatendimento.setText("ATENDIMENTO");
        btnatendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatendimentoActionPerformed(evt);
            }
        });

        btnfuncionarios.setText("FUNCIONARIOS");
        btnfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfuncionariosActionPerformed(evt);
            }
        });

        btncliente.setText("CLIENTE");
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });

        btnservicos.setText("SERVIÇO");
        btnservicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnservicosActionPerformed(evt);
            }
        });

        btnfechar.setText("Fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnlimpa)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(btnbusca))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbmstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmbarbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnfechar)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnfuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexcluir)
                .addGap(30, 30, 30)
                .addComponent(btnservicos)
                .addGap(33, 33, 33)
                .addComponent(btnatendimento)
                .addGap(36, 36, 36)
                .addComponent(btncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmbarbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbusca)
                            .addComponent(btnlimpa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnexcluir)
                            .addComponent(btnatendimento)
                            .addComponent(btnfuncionarios)
                            .addComponent(btncliente)
                            .addComponent(btnservicos)))
                    .addComponent(btnfechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
       try{
        int linha = tabela.getSelectedRow();
        
        if (linha == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "selecione um atendimento para excluir!");

            return;
        } else {

            int id;
            id = (int) tabela.getValueAt(linha, 0);
            a.excluir(id);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "atendimento excluído com sucesso!");
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"O atendimento nâo pode ser excluído" + e);
        }atualizarDados();
    
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfuncionariosActionPerformed
        
        funcionarios fun = new funcionarios(this);
        fun.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnfuncionariosActionPerformed

    private void btnatendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatendimentoActionPerformed
        
        atendimentos at = new atendimentos(this);
        at.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnatendimentoActionPerformed

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        
        clientes c = new clientes(this);
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnclienteActionPerformed

    private void cbmbarbeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmbarbeiroActionPerformed
    }//GEN-LAST:event_cbmbarbeiroActionPerformed

    private void btnbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaActionPerformed

            String data = txtdata.getText();
            String cliente = txtcliente.getText();
            String barbeiro = cbmbarbeiro.getSelectedItem().toString();

            if (data.equals("") || data.equals("__/__/____")) {
                data = "";
            }

            
           coringaJPA<barbeiro> bar = new coringaJPA<>(barbeiro.class);
            // barbeiro
            barbeiro barbeiroSelecionado = null;
            
            if (barbeiro.equals("-")) {
                barbeiro = "";
            }
            
            barbeiroSelecionado = bar.buscarPorNome(barbeiro);

            // status
            Boolean status = null;

            String statusSelecionado
                    = cbmstatus.getSelectedItem().toString();

            if (statusSelecionado.equals("Fechado")) {
                status = true;
            } else if (statusSelecionado.equals("Aberto")) {
                status = false;
            }

            List<atendimento> lista = a.pesquisarAtendimentos(data,cliente,barbeiroSelecionado,status);

            table.setRowCount(0);

                //enchendo
            for (atendimento f : lista) {

                table.addRow(new Object[]{
                    f.getIdatendimento(),
                    f.getCliente().getNome(),
                    f.getServico().getNome(),
                    f.getServico().getValor(),
                    f.getAtendente().getNome(),
                    f.getBarbeiro().getNome(),
                    f.getData(),
                    f.getHora(),
                    f.isStatus() ? "Fechado" : "Aberto"
                });
            }

    }//GEN-LAST:event_btnbuscaActionPerformed

    private void cbmstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmstatusActionPerformed
        
    }//GEN-LAST:event_cbmstatusActionPerformed

    private void btnlimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpaActionPerformed
        
        txtcliente.setText("");
        txtdata.setText("");
        cbmbarbeiro.setSelectedItem(1);
        cbmstatus.setSelectedItem(1);
        
        atualizarDados();
              
    }//GEN-LAST:event_btnlimpaActionPerformed

    private void btnservicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnservicosActionPerformed
        
        servicos s = new servicos(this);
        s.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnservicosActionPerformed

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        
        int linha = tabela.getSelectedRow();
        if (linha == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "selecione um atendimento para fechar!");
            return;
            
        } else {
        atendimento atend = new atendimento();
        
            coringaJPA<cliente> cli = new coringaJPA<>(cliente.class);
            coringaJPA<barbeiro> bar = new coringaJPA<>(barbeiro.class);
            coringaJPA<atendente> aten = new coringaJPA<>(atendente.class);
            coringaJPA<servico> ser = new coringaJPA(servico.class);
        
            int id = (int) tabela.getValueAt(linha, 0);
            String nomec = (String)tabela.getValueAt(linha, 1);
            String nomes = (String)tabela.getValueAt(linha, 2);
            String nomea = (String)tabela.getValueAt(linha, 4);
            String nomeb = (String)tabela.getValueAt(linha, 5);
            String data = (String)tabela.getValueAt(linha, 6);
            String hora = (String)tabela.getValueAt(linha, 7);
            String statusSelecionado = (String)tabela.getValueAt(linha, 8);
            boolean status  = false;

            if (statusSelecionado.equals("Fechado")) {
                return;
            }else{
                status = true;
            }
            
            atendente at = aten.buscarPorNome(nomea);
            cliente cl = cli.buscarPorNome(nomec);
            barbeiro ba = bar.buscarPorNome(nomeb);
            servico se = ser.buscarPorNome(nomes);
            
            atend.setIdatendimento(id);
            atend.setAtendente(at);
            atend.setCliente(cl);
            atend.setServico(se);
            atend.setBarbeiro(ba);
            atend.setData(data);
            atend.setHora(hora);
            atend.setStatus(status);
            
            
            a.atualizar(atend);
            
            javax.swing.JOptionPane.showMessageDialog(this,
                    "atendimento fechado!");
        }
       atualizarDados();
        
    }//GEN-LAST:event_btnfecharActionPerformed

    public void iniciartabela() {

        if (table == null) {

            table = new DefaultTableModel(
                    new Object[]{
                        "ID", "Cliente", "Serviço", "Valor Total", "Atendente", "Barbeiro", "Data", "Hora", "Status",}, 0) {

                @Override
                public boolean isCellEditable(int row, int column) {

                    return false; // ID não pode ser alterado

                }
            };

            tabela.setModel(table);
        }

        atualizarDados();
    }

    public void atualizarDados() {

        List<atendimento> lista = a.listar();

        table.setRowCount(0);

        for (atendimento f : lista) {

            table.addRow(new Object[]{
                f.getIdatendimento(),
                f.getCliente().getNome(),
                f.getServico().getNome(),
                f.getServico().getValor(),
                f.getAtendente().getNome(),
                f.getBarbeiro().getNome(),
                f.getData(),
                f.getHora(),
                f.isStatus() ? "Fechado" : "Aberto"
            });
        }
        carregarBox();
    }

    private void carregarBox() {

        coringaJPA<barbeiro> b = new coringaJPA<>(barbeiro.class);

        cbmbarbeiro.removeAllItems();
        cbmbarbeiro.addItem("-");
        
        List<barbeiro> bar = b.listar();
        
        for (barbeiro bb : bar) {
            
            cbmbarbeiro.addItem(bb.getNome());
        }
        
        MaskFormatter mascara = null;

        try {
            mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
            txtdata.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascara)
            );
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatendimento;
    private javax.swing.JButton btnbusca;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnfechar;
    private javax.swing.JButton btnfuncionarios;
    private javax.swing.JButton btnlimpa;
    private javax.swing.JButton btnservicos;
    private javax.swing.JComboBox<String> cbmbarbeiro;
    private javax.swing.JComboBox<String> cbmstatus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JFormattedTextField txtdata;
    // End of variables declaration//GEN-END:variables
}
